name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3.0.0
    - name: set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
